global:
  included_classes: ["Insecta"]
  verbose: false
  overwrite: true

paths:
  src_dataset: "/home/quydx/mcunet_full/inat_2017"
  dst_dataset: "/home/quydx/iNaturelist_transfer_learning_pytorch/data/haute_garonne"
  web_crawl_output_json: "/home/quydx/iNaturelist_transfer_learning_pytorch/output/haute_garonne.json"
  output_dir: "/home/quydx/iNaturelist_transfer_learning_pytorch/output"

web_crawl:
  total_pages: 104
  base_url: "https://www.inaturalist.org/check_lists/32961-Haute-Garonne-Check-List?page="
  delay_between_requests: 1.0

train_val_split:
  train_size: 0.8
  random_state: 42
  dominant_threshold: 0.9